# This is a basic workflow to help you get started with Actions

name: head-artifacts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Add conda to system path
        run: |
          # $CONDA is an env variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base
      - name: Install exporter
        run: |
          pip install -e ./python/
      - name: Prepare versioned directory
        run: |
          export CI_META_PREFIX=clix-meta-data
          export CI_META_VERSION=$(ci-meta-exporter -v)
          echo 'devel' >ci-meta-version.txt
          export CI_META_NAME=${CI_META_PREFIX}-${CI_META_VERSION}
          mkdir $CI_META_NAME
          cp master_table.xls README.md LICENSE.txt $CI_META_NAME/
          cd $CI_META_NAME
          ci-meta-exporter ./master_table.xls
          cd ..
          export CI_META_ARCHIVE_BASE=${CI_META_PREFIX}-devel
          echo "CI_META_ARCHIVE_BASE=$CI_META_ARCHIVE_BASE" >> $GITHUB_ENV
          echo "CI_META_NAME=$CI_META_NAME" >> $GITHUB_ENV
      - name: Upload normal line endings version
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CI_META_ARCHIVE_BASE }}-linux
          path: ${{ env.CI_META_NAME }}
      - name: Create windows line endings version
        run: |
          cd $CI_META_NAME
          unix2dos README.md LICENSE.txt *.yml
          cd ..
      - name: Upload windows line endings version
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CI_META_ARCHIVE_BASE }}-win
          path: ${{ env.CI_META_NAME }}
      - name: Create mac line endings version
        run: |
          cd $CI_META_NAME
          dos2unix README.md LICENSE.txt *.yml
          unix2mac README.md LICENSE.txt *.yml
          cd ..
      - name: Upload mac line endings version
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.CI_META_ARCHIVE_BASE }}-osx
          path: ${{ env.CI_META_NAME }}
