# This is a basic workflow to help you get started with Actions

name: head-artifacts

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run a multi-line script
        run: |
          conda env update -n base --file bitbucket-environment.yml
          pip install -e ./python/
          export CI_META_PREFIX=cf-index-meta-data
          export CI_META_VERSION=$(ci-meta-exporter -v)
          echo 'devel' >ci-meta-version.txt
          export CI_META_NAME=${CI_META_PREFIX}-${CI_META_VERSION}
          mkdir $CI_META_NAME
          cp master_table.xls README.md LICENSE.txt $CI_META_NAME
          cd $CI_META_NAME
          ci-meta-exporter ./master_table.xls
          cd ..
          tar cvf ${CI_META_PREFIX}-devel.tar.gz $CI_META_NAME
          cd $CI_META_NAME
          unix2dos README.md LICENSE.txt *.yml
          cd ..
          zip -r ${CI_META_PREFIX}-devel.zip $CI_META_NAME
